version: "2.2"
services:
  server:
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src/static:/src/static
    links:
      - web:web
    ports:
      - "80:80"

  web:
    image: smihailova/simple-devops-image:latest
    extends:
      file: docker-compose.base.yml
      service: web
    expose:
      - "8000"
    command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-
